export const SOLUTION_AREAS = [
  { id: 'COMPUTE', label: 'Compute Solutions' },
  { id: 'CLOUD', label: 'Cloud Solutions' },
  { id: 'NETWORKING', label: 'Networking Solutions' },
  { id: 'APPLICATION', label: 'Application Solutions' },
  { id: 'CYBER_SECURITY', label: 'Cyber Security Solutions' },
  { id: 'DATA_CENTRE', label: 'Data Centre Solutions' },
  { id: 'MANAGED_SERVICES', label: 'Managed Services' },
  { id: 'VIDEO_CONFERENCING', label: 'High-definition VC Systems' },
  { id: 'SPECIALIZATION', label: 'Specialization Zone (EOL/EOSL/TPM)' },
  { id: 'Accessories', label: 'Accessories' },
  { id: 'Other', label: 'Other' },
];

export const OEM_LIST = [
  'OpenText',
  'Scalefusion',
  'Seceon',
  'Cohesity',
  'Crest ERP',
  'HP',
  'Hewlett Packard Enterprise (HPE)',
  'Dell',
  'Lenovo',
  'Acer',
  'Microsoft Azure',
  'Amazon Web Services (AWS)',
  'Google',
  'IBM',
  'Nutanix',
  'NetApp',
  'Hitachi Vantara',
  'Cisco',
  'Fortinet',
  'Palo Alto Networks',
  'Sophos',
  'Check Point',
  'APC',
  'Vertiv',
  'Emerson',
  'Logitech',
  'Samsung',
  'Trend Micro',
  'F5',
  'Tenable',
  'Microsoft',
  'VMware',
  'Zoho',
  'SolarWinds',
  'Freshworks',
  'ASUS',
  'Max Services',
  'Red Hat',
  'Veritas',
  'Konica Minolta',
  'Accops',
  'EPOS',
  'Adobe',
  'Hikvision',
  'Adani',
  'Schneider Electric',
  'Novo Nordisk',
  'Xerox',
  'Commvault',
];
